AWSTemplateFormatVersion: '2010-09-09'
Description: 'Minimum VPC Endpoints for HIPAA RNA-Seq Pipeline - Essential Services Only'

Parameters:
  VpcId:
    Type: String
    Description: VPC ID (e.g., vpc-xxxxx)
    Default: vpc-xxxxxxxxxxxxxxxxx
  
  PrivateSubnet1Id:
    Type: String
    Description: Private Subnet AZ1 ID
    Default: subnet-xxxxxxxxxxxxxxxxx
  
  PrivateSubnet2Id:
    Type: String
    Description: Private Subnet AZ2 ID
    Default: subnet-xxxxxxxxxxxxxxxxx
  
  RouteTableId:
    Type: String
    Description: Private Route Table ID
    Default: rtb-xxxxxxxxxxxxxxxxx

Resources:
  # Security Group for Interface Endpoints
  VPCEndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: rna-seq-vpc-endpoint-sg
      GroupDescription: Security group for VPC endpoints
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 10.0.0.0/16
          Description: Allow HTTPS from VPC
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Allow all outbound
      Tags:
        - Key: Name
          Value: rna-seq-vpc-endpoint-sg

  # S3 Gateway Endpoint (FREE - Always On)
  S3GatewayEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: Gateway
      VpcId: !Ref VpcId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      RouteTableIds:
        - !Ref RouteTableId
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:*'
            Resource: '*'

  # ECR API Endpoint (REQUIRED for Docker)
  ECRApiEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: Interface
      VpcId: !Ref VpcId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.ecr.api'
      SubnetIds:
        - !Ref PrivateSubnet1Id
        - !Ref PrivateSubnet2Id
      SecurityGroupIds:
        - !Ref VPCEndpointSecurityGroup
      PrivateDnsEnabled: true

  # ECR Docker Endpoint (REQUIRED for Docker)
  ECRDockerEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: Interface
      VpcId: !Ref VpcId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.ecr.dkr'
      SubnetIds:
        - !Ref PrivateSubnet1Id
        - !Ref PrivateSubnet2Id
      SecurityGroupIds:
        - !Ref VPCEndpointSecurityGroup
      PrivateDnsEnabled: true

  # CloudWatch Logs Endpoint (REQUIRED for logging)
  LogsEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: Interface
      VpcId: !Ref VpcId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.logs'
      SubnetIds:
        - !Ref PrivateSubnet1Id
        - !Ref PrivateSubnet2Id
      SecurityGroupIds:
        - !Ref VPCEndpointSecurityGroup
      PrivateDnsEnabled: true

  # AWS Batch Endpoint
  BatchEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: Interface
      VpcId: !Ref VpcId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.batch'
      SubnetIds:
        - !Ref PrivateSubnet1Id
        - !Ref PrivateSubnet2Id
      SecurityGroupIds:
        - !Ref VPCEndpointSecurityGroup
      PrivateDnsEnabled: true

  # ECS Endpoint (Batch uses ECS under the hood)
  ECSEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: Interface
      VpcId: !Ref VpcId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.ecs'
      SubnetIds:
        - !Ref PrivateSubnet1Id
        - !Ref PrivateSubnet2Id
      SecurityGroupIds:
        - !Ref VPCEndpointSecurityGroup
      PrivateDnsEnabled: true

  # ECS Agent Endpoint (Required for ECS tasks)
  ECSAgentEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: Interface
      VpcId: !Ref VpcId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.ecs-agent'
      SubnetIds:
        - !Ref PrivateSubnet1Id
        - !Ref PrivateSubnet2Id
      SecurityGroupIds:
        - !Ref VPCEndpointSecurityGroup
      PrivateDnsEnabled: true

  # ECS Telemetry Endpoint (Required for ECS metrics)
  ECSTelemetryEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: Interface
      VpcId: !Ref VpcId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.ecs-telemetry'
      SubnetIds:
        - !Ref PrivateSubnet1Id
        - !Ref PrivateSubnet2Id
      SecurityGroupIds:
        - !Ref VPCEndpointSecurityGroup
      PrivateDnsEnabled: true

Outputs:
  S3EndpointId:
    Description: S3 Gateway Endpoint ID (FREE - Keep Always On)
    Value: !Ref S3GatewayEndpoint
    Export:
      Name: !Sub '${AWS::StackName}-S3EndpointId'
  
  VPCEndpointSecurityGroupId:
    Description: Security Group for VPC Endpoints
    Value: !Ref VPCEndpointSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-EndpointSG'
  
  ECRApiEndpointId:
    Description: ECR API Endpoint ID
    Value: !Ref ECRApiEndpoint
  
  ECRDockerEndpointId:
    Description: ECR Docker Endpoint ID
    Value: !Ref ECRDockerEndpoint
  
  LogsEndpointId:
    Description: CloudWatch Logs Endpoint ID
    Value: !Ref LogsEndpoint
  
  BatchEndpointId:
    Description: AWS Batch Endpoint ID
    Value: !Ref BatchEndpoint
  
  EstimatedMonthlyCost:
    Description: Estimated monthly cost for interface endpoints
    Value: "~$49 per month (7 interface endpoints × $7)"